import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { Observable, catchError, throwError } from 'rxjs';
import { Cve } from '../models/cve.model';

@Injectable({
  providedIn: 'root',
})
export class CveService {
  private apiUrl = 'http://localhost:8080';

  constructor(private http: HttpClient) {}

  getAllCves(): Observable<Cve[]> {
    return this.http
      .get<Cve[]>(`${this.apiUrl}` + '/api/cves/cve')
      .pipe(catchError(this.handleError));
  }

  getCveById(id: string): Observable<Cve> {
    return this.http
      .get<Cve>(`${this.apiUrl}/api/cves/cve/${id}`)
      .pipe(catchError(this.handleError));
}

  handleError(error: HttpErrorResponse) {
    if (error.status === 0) {
      // A client-side or network error occurred. Handle it accordingly.
      console.error('An error occurred:', error.error);
    } else {
      // The backend returned an unsuccessful response code.
      // The response body may contain clues as to what went wrong.
      console.error(
        `Backend returned code ${error.status}, body was: `,
        error.error
      );
    }
    // Return an observable with a user-facing error message.
    return throwError(
      () => new Error('Something bad happened; please try again later.')
    );
  }
}
